# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "activesupport", '6.0.0'
gem "nokogiri"
gem "faraday"
gem "tzinfo", '~> 1.1'